(()=>{
const B=window.TEXTILE_BATCH,KEY='ruthie-open-font-library-b12';let state={};try{state=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){}
const $=q=>document.querySelector(q),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const app=$('#app'),nav=$('#nav'),statusEl=$('#status'),exportBox=$('#exportBox');
const groups={
'KNIT / COLORWORK':'Fonts designed around stitch-count grids and real colorwork charts.',
'HISTORIC CROSS-STITCH ENGINES':'Historical needlework alphabets turned into programmable contemporary fonts.',
'WOVEN / MATERIAL SYSTEMS':'Letterforms whose construction comes from weave, embroidery or material modules.',
'ACTUAL MACHINE-EMBROIDERY ALPHABETS':'Not approximations: Ink/Stitch production systems with stitch metadata, scale limits and embroidery-specific geometry.'};
function get(o){return state[o.id]||(state[o.id]={vote:'',face:o.native?o.face:o.faces[0].label,features:[],notes:''})}
function save(){localStorage.setItem(KEY,JSON.stringify(state));status()}
function status(msg){if(msg){statusEl.textContent=msg;return}const d=B.candidates.filter(o=>get(o).vote).length;statusEl.textContent=`${d}/${B.candidates.length} decided · ${B.approvedBefore}/${B.targetApproved} approved before this round`}
function addFaces(){const st=document.createElement('style');st.textContent=B.candidates.flatMap(o=>(o.faces||[]).map(f=>`@font-face{font-family:'${f.family}';src:url('${f.url}') format('${f.format||'woff2'}');font-display:swap;}`)).join('\n');document.head.append(st)}
function samples(){return[['TEXTILE','SPATIAL PRESS'],['LABEL','ORBITER · WITNESS · TRACE'],['GARMENT','PORTALES · 19 JAN 1992 · 17:57'],['GLYPHS','ABCDEFGHIJKLM NOPQRSTUVWXYZ · abcdefghijklm nopqrstuvwxyz · 0123456789'],['BODY','A textile alphabet has to survive material: thread thickness, stitch count, weave direction, scale, tension, and the way a surface is actually made.']]}
function apply(o,c){if(o.native)return;const s=get(o),f=o.faces.find(x=>x.label===s.face)||o.faces[0],box=c.querySelector('.samples'),badge=c.querySelector('.font-load');box.style.fontFamily=`'${f.family}'`;box.style.fontFeatureSettings=(s.features||[]).map(x=>`"${x}" 1`).join(',')||'normal';box.style.fontSynthesis='none';badge.textContent='loading type…';badge.className='font-load';document.fonts?.load(`32px "${f.family}"`,'SPATIAL PRESS').then(x=>{badge.textContent=x.length?'font loaded ✓':'font failed to load';badge.className='font-load '+(x.length?'ok':'bad')}).catch(()=>{badge.textContent='font failed to load';badge.className='font-load bad'});c.dataset.active='1'}
function render(){addFaces();let last='',io=('IntersectionObserver'in window)?new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const c=e.target,o=B.candidates.find(x=>x.id===c.id);if(o&&!o.native&&!c.dataset.active)apply(o,c);io.unobserve(c)}),{rootMargin:'900px 0px'}):null;
B.candidates.forEach((o,i)=>{if(o.group!==last){const g=document.createElement('div');g.className='group-head';g.innerHTML=`<div class="group-kicker">TEXTILE LANE</div><div class="group-title">${esc(o.group)}</div><div class="group-note">${esc(groups[o.group])}</div>`;app.append(g);last=o.group}
const a=document.createElement('a');a.href='#'+o.id;a.textContent=String(i+1).padStart(2,'0')+' '+o.name;nav.append(a);const s=get(o),c=document.createElement('section');c.className='card';c.id=o.id;c.innerHTML=`<div class="head"><div class="num">${String(i+1).padStart(2,'0')}</div><div><h2>${esc(o.name)}</h2><div class="artist">${esc(o.artist)}</div></div></div><p class="story">${esc(o.story)}</p><div class="license">${esc(o.license)}</div><div class="material">${esc(o.meta||'')}</div><div class="controls"><div class="control-label">${o.native?'SOURCE STATE':'SUPPLIED CUTS / STATES'}</div><div class="row faces"></div>${o.features?.length?'<div class="control-label" style="margin-top:12px">OPENTYPE</div><div class="row features"></div>':''}<div class="font-load ${o.native?'ok':''}">${o.native?'stitch-native source ✓':'waiting to load…'}</div></div>${o.native?`<div class="native"><div class="native-label">ACTUAL INK/STITCH PRODUCTION PREVIEW</div><img loading="lazy" src="${o.preview}" alt="${esc(o.name)} official stitch preview"><a href="${o.source}" target="_blank" rel="noopener">Open official stitch source ↗</a></div>`:'<div class="samples"></div>'}<textarea class="notes" placeholder="Optional note…">${esc(s.notes)}</textarea><div class="decision-wrap"><div class="decision-label">KEEP THIS IN THE LIBRARY?</div><div class="votes"></div></div>`;
const fr=c.querySelector('.faces');if(o.native){const b=document.createElement('button');b.className='pill active';b.textContent=o.face;fr.append(b)}else o.faces.forEach(f=>{const b=document.createElement('button');b.className='pill'+(s.face===f.label?' active':'');b.textContent=f.label;b.onclick=()=>{s.face=f.label;fr.querySelectorAll('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');apply(o,c);save()};fr.append(b)});
if(o.features?.length){const rr=c.querySelector('.features');o.features.forEach(tag=>{const b=document.createElement('button');b.className='pill'+((s.features||[]).includes(tag)?' active':'');b.textContent=tag;b.onclick=()=>{s.features=s.features||[];s.features=s.features.includes(tag)?s.features.filter(x=>x!==tag):[...s.features,tag];b.classList.toggle('active');if(!o.native)apply(o,c);save()};rr.append(b)})}
if(!o.native){const sb=c.querySelector('.samples');samples().forEach(([lab,text])=>{const d=document.createElement('div');d.className='sample'+(lab==='BODY'?' body':'');d.innerHTML=`<div class="sample-label">${lab}</div><div class="sample-text" contenteditable="true" spellcheck="false">${esc(text)}</div>`;sb.append(d)})}
c.querySelector('.notes').oninput=e=>{s.notes=e.target.value;save()};const vr=c.querySelector('.votes');['YES','NO'].forEach(v=>{const b=document.createElement('button');b.className='pill'+(s.vote===v?' active':'');b.textContent=v;b.onclick=()=>{s.vote=v;vr.querySelectorAll('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');save()};vr.append(b)});app.append(c);if(!o.native){if(io)io.observe(c);else apply(o,c)}});status()}
$('#global').oninput=e=>{if(e.target.value)document.querySelectorAll('.samples .sample:not(.body) .sample-text').forEach(x=>x.textContent=e.target.value)};$('#size').oninput=e=>{document.documentElement.style.setProperty('--size',e.target.value+'px');$('#sizeVal').textContent=e.target.value};
$('#copy').onclick=async()=>{document.querySelectorAll('.card').forEach(c=>{const o=B.candidates.find(x=>x.id===c.id);if(o)get(o).notes=c.querySelector('.notes').value});save();const payload={batch:12,picks:B.candidates.map((o,i)=>{const s=get(o);return{number:i+1,name:o.name,vote:s.vote,face:s.face,features:s.features||[],notes:s.notes||''}})},text=JSON.stringify(payload,null,2);exportBox.textContent=text;try{await navigator.clipboard.writeText(text);exportBox.hidden=true;status('Copied ✓');setTimeout(()=>status(),4500)}catch(e){exportBox.hidden=false;status('Copy blocked — payload shown below');exportBox.scrollIntoView({behavior:'smooth'})}};
render();
})();
